#mybatis:
#  type-aliases-package: org.codework.tools.gb2260.entity
#  type-handlers-package: org.codework.tools.gb2260.handler

mybatis-plus:
  typeAliasesPackage: org.codework.tools.gb2260.entity
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 1
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #配置DB类型(主要作用避免GlobalConfigUtils setMetaData Fail 错误, #https://gitee.com/baomidou/mybatis-plus/issues/IL3U8)
    db-config:
      db-type: MYSQL
  configuration:
    #配置返回数据库(column下划线命名&&返回java实体是驼峰命名)，自动匹配无需as（没开启这个，SQL需要写as： select user_id as userId）
    map-underscore-to-camel-case: true
    cache-enabled: false

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gb2260?useUnicode=true&characterEncoding=utf-8&useSSL=false&useAffectedRows=true
    username: root
    password: 34231724
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    database: 10
    host: localhost
    port: 6379
    password: 34231724

server:
  port: 8080

logging:
  level:
    root: INFO
    # 不想TableInfoHelper输出Cache为空的warn信息
    com.baomidou.mybatisplus.core.toolkit.TableInfoHelper: ERROR